/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSessionsRouteImport } from './routes/_authenticated.sessions'
import { Route as AuthenticatedPipelinesRouteImport } from './routes/_authenticated.pipelines'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated.integrations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedConversationsRouteImport } from './routes/_authenticated.conversations'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated.contacts'
import { Route as AuthenticatedAutomationsRouteImport } from './routes/_authenticated.automations'
import { Route as AuthenticatedConversationsIndexRouteImport } from './routes/_authenticated.conversations.index'
import { Route as AuthenticatedConversationsThreadIdRouteImport } from './routes/_authenticated.conversations.$threadId'
import { Route as ApiPublicEngineIngestRouteImport } from './routes/api/public/engine/ingest'
import { Route as ApiPublicEngineCommandsRouteImport } from './routes/api/public/engine/commands'
import { Route as ApiPublicCronDispatchRouteImport } from './routes/api/public/cron/dispatch'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSessionsRoute = AuthenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPipelinesRoute = AuthenticatedPipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConversationsRoute =
  AuthenticatedConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAutomationsRoute =
  AuthenticatedAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConversationsIndexRoute =
  AuthenticatedConversationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConversationsRoute,
  } as any)
const AuthenticatedConversationsThreadIdRoute =
  AuthenticatedConversationsThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedConversationsRoute,
  } as any)
const ApiPublicEngineIngestRoute = ApiPublicEngineIngestRouteImport.update({
  id: '/api/public/engine/ingest',
  path: '/api/public/engine/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEngineCommandsRoute = ApiPublicEngineCommandsRouteImport.update({
  id: '/api/public/engine/commands',
  path: '/api/public/engine/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronDispatchRoute = ApiPublicCronDispatchRouteImport.update({
  id: '/api/public/cron/dispatch',
  path: '/api/public/cron/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/conversations': typeof AuthenticatedConversationsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/pipelines': typeof AuthenticatedPipelinesRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/conversations/$threadId': typeof AuthenticatedConversationsThreadIdRoute
  '/conversations/': typeof AuthenticatedConversationsIndexRoute
  '/api/public/cron/dispatch': typeof ApiPublicCronDispatchRoute
  '/api/public/engine/commands': typeof ApiPublicEngineCommandsRoute
  '/api/public/engine/ingest': typeof ApiPublicEngineIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/pipelines': typeof AuthenticatedPipelinesRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/conversations/$threadId': typeof AuthenticatedConversationsThreadIdRoute
  '/conversations': typeof AuthenticatedConversationsIndexRoute
  '/api/public/cron/dispatch': typeof ApiPublicCronDispatchRoute
  '/api/public/engine/commands': typeof ApiPublicEngineCommandsRoute
  '/api/public/engine/ingest': typeof ApiPublicEngineIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/automations': typeof AuthenticatedAutomationsRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/conversations': typeof AuthenticatedConversationsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/pipelines': typeof AuthenticatedPipelinesRoute
  '/_authenticated/sessions': typeof AuthenticatedSessionsRoute
  '/_authenticated/conversations/$threadId': typeof AuthenticatedConversationsThreadIdRoute
  '/_authenticated/conversations/': typeof AuthenticatedConversationsIndexRoute
  '/api/public/cron/dispatch': typeof ApiPublicCronDispatchRoute
  '/api/public/engine/commands': typeof ApiPublicEngineCommandsRoute
  '/api/public/engine/ingest': typeof ApiPublicEngineIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/automations'
    | '/contacts'
    | '/conversations'
    | '/dashboard'
    | '/integrations'
    | '/pipelines'
    | '/sessions'
    | '/conversations/$threadId'
    | '/conversations/'
    | '/api/public/cron/dispatch'
    | '/api/public/engine/commands'
    | '/api/public/engine/ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/automations'
    | '/contacts'
    | '/dashboard'
    | '/integrations'
    | '/pipelines'
    | '/sessions'
    | '/conversations/$threadId'
    | '/conversations'
    | '/api/public/cron/dispatch'
    | '/api/public/engine/commands'
    | '/api/public/engine/ingest'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/automations'
    | '/_authenticated/contacts'
    | '/_authenticated/conversations'
    | '/_authenticated/dashboard'
    | '/_authenticated/integrations'
    | '/_authenticated/pipelines'
    | '/_authenticated/sessions'
    | '/_authenticated/conversations/$threadId'
    | '/_authenticated/conversations/'
    | '/api/public/cron/dispatch'
    | '/api/public/engine/commands'
    | '/api/public/engine/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiPublicCronDispatchRoute: typeof ApiPublicCronDispatchRoute
  ApiPublicEngineCommandsRoute: typeof ApiPublicEngineCommandsRoute
  ApiPublicEngineIngestRoute: typeof ApiPublicEngineIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pipelines': {
      id: '/_authenticated/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof AuthenticatedPipelinesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conversations': {
      id: '/_authenticated/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthenticatedConversationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/automations': {
      id: '/_authenticated/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AuthenticatedAutomationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conversations/': {
      id: '/_authenticated/conversations/'
      path: '/'
      fullPath: '/conversations/'
      preLoaderRoute: typeof AuthenticatedConversationsIndexRouteImport
      parentRoute: typeof AuthenticatedConversationsRoute
    }
    '/_authenticated/conversations/$threadId': {
      id: '/_authenticated/conversations/$threadId'
      path: '/$threadId'
      fullPath: '/conversations/$threadId'
      preLoaderRoute: typeof AuthenticatedConversationsThreadIdRouteImport
      parentRoute: typeof AuthenticatedConversationsRoute
    }
    '/api/public/engine/ingest': {
      id: '/api/public/engine/ingest'
      path: '/api/public/engine/ingest'
      fullPath: '/api/public/engine/ingest'
      preLoaderRoute: typeof ApiPublicEngineIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/engine/commands': {
      id: '/api/public/engine/commands'
      path: '/api/public/engine/commands'
      fullPath: '/api/public/engine/commands'
      preLoaderRoute: typeof ApiPublicEngineCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/dispatch': {
      id: '/api/public/cron/dispatch'
      path: '/api/public/cron/dispatch'
      fullPath: '/api/public/cron/dispatch'
      preLoaderRoute: typeof ApiPublicCronDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedConversationsRouteChildren {
  AuthenticatedConversationsThreadIdRoute: typeof AuthenticatedConversationsThreadIdRoute
  AuthenticatedConversationsIndexRoute: typeof AuthenticatedConversationsIndexRoute
}

const AuthenticatedConversationsRouteChildren: AuthenticatedConversationsRouteChildren =
  {
    AuthenticatedConversationsThreadIdRoute:
      AuthenticatedConversationsThreadIdRoute,
    AuthenticatedConversationsIndexRoute: AuthenticatedConversationsIndexRoute,
  }

const AuthenticatedConversationsRouteWithChildren =
  AuthenticatedConversationsRoute._addFileChildren(
    AuthenticatedConversationsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAutomationsRoute: typeof AuthenticatedAutomationsRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedConversationsRoute: typeof AuthenticatedConversationsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedPipelinesRoute: typeof AuthenticatedPipelinesRoute
  AuthenticatedSessionsRoute: typeof AuthenticatedSessionsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAutomationsRoute: AuthenticatedAutomationsRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedConversationsRoute: AuthenticatedConversationsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedPipelinesRoute: AuthenticatedPipelinesRoute,
  AuthenticatedSessionsRoute: AuthenticatedSessionsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiPublicCronDispatchRoute: ApiPublicCronDispatchRoute,
  ApiPublicEngineCommandsRoute: ApiPublicEngineCommandsRoute,
  ApiPublicEngineIngestRoute: ApiPublicEngineIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
