-- Etapa: Adición de campos CRM a la tabla contacts

ALTER TABLE public.contacts
ADD COLUMN IF NOT EXISTS origin TEXT,
ADD COLUMN IF NOT EXISTS entry_date TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS exit_date TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS deal_value NUMERIC(15,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS company TEXT,
ADD COLUMN IF NOT EXISTS position TEXT,
ADD COLUMN IF NOT EXISTS interested_products TEXT,
ADD COLUMN IF NOT EXISTS observations TEXT;
