// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'
import { nodeRealtimeWebSocket } from './node-websocket-transport'



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    let authHeader = request.headers.get('authorization');
    let token = authHeader?.replace('Bearer ', '') ?? '';

    // Fallback: leer token desde cookies si no hay header de autorización
    if (!token) {
      const cookieHeader = request.headers.get('cookie') ?? '';
      const sbTokenMatch = cookieHeader.match(/sb-[^=]+=([^;]+)/);
      if (sbTokenMatch?.[1]) {
        try {
          const parsed = JSON.parse(decodeURIComponent(sbTokenMatch[1]));
          token = parsed.access_token ?? parsed.token ?? '';
        } catch {
          token = '';
        }
      }
    }

    if (!token) {
      throw new Error('Unauthorized: No authorization header or cookie token provided');
    }

    if (authHeader && !authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }
    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
        realtime: nodeRealtimeWebSocket ? { transport: nodeRealtimeWebSocket } : undefined,
      }
    );

    // Validar token con getUser (primario) y getClaims (fallback)
    let userId: string | undefined;
    let claimsData: any = undefined;

    try {
      const { data: userData, error: userError } = await supabase.auth.getUser(token);
      if (userData?.user?.id) {
        userId = userData.user.id;
        claimsData = userData.user.app_metadata;
      }
    } catch {
      // Ignorar error y probar fallback
    }

    if (!userId) {
      const { data: claimsRes, error: claimsError } = await supabase.auth.getClaims(token);
      if (!claimsError && claimsRes?.claims?.sub) {
        userId = claimsRes.claims.sub as string;
        claimsData = claimsRes.claims;
      } else {
        console.error('[Supabase Auth Middleware] Invalid token error:', claimsError?.message);
        throw new Error('Unauthorized: Invalid or expired token');
      }
    }

    // Usuarios desactivados por el master no pueden usar la API
    try {
      const { createClient: createAdminClient } = await import('@supabase/supabase-js');
      const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
      if (serviceKey && SUPABASE_URL) {
        const admin = createAdminClient(SUPABASE_URL, serviceKey, {
          auth: { persistSession: false, autoRefreshToken: false },
        });
        const { data: profile } = await admin
          .from('profiles')
          .select('is_active')
          .eq('id', userId)
          .maybeSingle();
        if (profile && (profile as { is_active?: boolean }).is_active === false) {
          throw new Error('Cuenta desactivada. Contacta al administrador de la plataforma.');
        }
      }
    } catch (err) {
      if (err instanceof Error && err.message.includes('desactivada')) throw err;
      // Si falta columna/migración, no bloquear el resto de la app
    }

    return next({
      context: {
        supabase,
        userId: userId!,
        claims: claimsData,
      },
    });
  },
);
